# Generated by Django 4.2.7 on 2023-11-25 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("uploader", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Avaliador",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name_plural": "Avaliadores",
            },
        ),
        migrations.CreateModel(
            name="Criterio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Equipe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=50)),
                ("nota", models.IntegerField(default=0)),
                (
                    "foto",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="uploader.image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255)),
                ("data", models.DateField(max_length=255)),
                ("hora", models.TimeField(max_length=255)),
                ("local", models.CharField(max_length=255)),
                ("observacoes", models.CharField(blank=True, max_length=500, null=True)),
                ("data_inscricao_inicio", models.DateField()),
                ("data_inscricao_fim", models.DateField()),
                (
                    "foto",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="uploader.image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participante",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="participantes", to="core.equipe"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participantes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nota", models.IntegerField(default=0)),
                (
                    "avaliador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="notas", to="core.avaliador"
                    ),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="notas", to="core.criterio"
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="notas", to="core.equipe"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instituicao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                (
                    "foto",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="uploader.image",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Instituições",
            },
        ),
        migrations.CreateModel(
            name="Hackathon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "avaliadores",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="hackathon", to="core.avaliador"
                    ),
                ),
                (
                    "equipes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="hackathon", to="core.equipe"
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="hackathon", to="core.evento"
                    ),
                ),
                (
                    "instituicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="hackathon", to="core.instituicao"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evento",
            name="instituicao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="instituicao", to="core.instituicao"
            ),
        ),
        migrations.AddField(
            model_name="criterio",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="criterios", to="core.evento"
            ),
        ),
        migrations.AddField(
            model_name="avaliador",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="avaliadores", to="core.evento"
            ),
        ),
        migrations.AddField(
            model_name="avaliador",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="avaliadores", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
