# Generated by Django 4.2.7 on 2023-11-25 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipe",
            name="evento",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, related_name="equipes", to="core.evento"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Hackathon",
        ),
    ]
