# Generated by Django 4.2.7 on 2023-11-24 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_avaliador"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=50)),
                ("nota", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255)),
                ("data", models.DateField(max_length=255)),
                ("hora", models.TimeField(max_length=255)),
                ("local", models.CharField(max_length=255)),
                ("observacoes", models.CharField(blank=True, max_length=500, null=True)),
                ("data_inscricao_inicio", models.DateField()),
                ("data_inscricao_fim", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Instituicao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Instituições",
            },
        ),
        migrations.CreateModel(
            name="Participante",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("idade", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Hackathon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "avaliadores",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="hackathon", to="core.avaliador"
                    ),
                ),
                (
                    "equipes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="hackathon", to="core.equipe"
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="hackathon", to="core.evento"
                    ),
                ),
                (
                    "instituicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="hackathon", to="core.instituicao"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evento",
            name="instituicao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="instituicao", to="core.instituicao"
            ),
        ),
        migrations.AddField(
            model_name="equipe",
            name="participantes",
            field=models.ManyToManyField(related_name="equipes", to="core.participante"),
        ),
    ]
