# Generated by Django 4.2.7 on 2023-11-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_user_foto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participante",
            name="equipe",
        ),
        migrations.AddField(
            model_name="equipe",
            name="membros",
            field=models.ManyToManyField(related_name="equipes", to="core.participante"),
        ),
    ]
