# Generated by Django 4.2.7 on 2023-11-25 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_avaliador_foto_equipe_foto_evento_foto_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participante",
            name="email",
        ),
        migrations.RemoveField(
            model_name="participante",
            name="idade",
        ),
        migrations.RemoveField(
            model_name="participante",
            name="nome",
        ),
        migrations.AddField(
            model_name="participante",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participantes",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="data_nasc",
            field=models.DateField(blank=True, null=True),
        ),
    ]
