# Generated by Django 4.2.7 on 2023-11-25 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_equipe_foto_remove_equipe_nota"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nota",
            name="criterio",
        ),
    ]
