# Generated by Django 4.2.7 on 2023-11-25 01:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_participante_email_remove_participante_idade_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="data_nasc",
            new_name="data_nascimento",
        ),
    ]
