# Generated by Django 4.2.7 on 2023-11-25 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_nota_criterio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nota",
            options={"verbose_name_plural": "Notas"},
        ),
        migrations.RenameField(
            model_name="nota",
            old_name="nota",
            new_name="avaliacao",
        ),
    ]
